Repository aio-libs/yarl, pull requests merged in 2020-09, with the labels that each got.

#503 Do not requote arguments of URL.build() and with_xxx()
  CHANGES/502.bugfix
  CHANGES/504.bugfix
  tests/test_url.py
  tests/test_url_build.py
  tests/test_url_update_netloc.py
  yarl/_url.py
Labels: bot:chronographer:provided

#505 Allow int and float Subclasses in Query
  CHANGES/492.feature
  docs/api.rst
  docs/spelling_wordlist.txt
  tests/test_update_query.py
  yarl/_url.py
Labels: bot:chronographer:provided

#512 Fix `URL.human_repr()` to always return URLs equivalent to the source
  CHANGES/511.bugfix
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided, bug

#518 Add an issue template chooser config
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#522 Migrate issue templates from aiohttp and link discussions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#523 Disable the suggestion to use a blank issue tmpl
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement
