Repository aio-libs/yarl, pull requests merged in 2022-12, with the labels that each got.

#790 Switch Python 3.11 to stable release in CI
  .github/workflows/ci.yml
Labels: enhancement, bot:chronographer:skip

#791 Add project description to README
  README.rst
Labels: bot:chronographer:skip

#798 Fix linter CI stage: replace libenchant-dev with libenchant-2-dev
  .github/workflows/ci.yml
Labels: bot:chronographer:skip

#793 Fix to URL.with_port() input filtering
  CHANGES/793.bugfix.rst
  tests/test_url_update_netloc.py
  yarl/_url.py
Labels: bot:chronographer:provided

#792 Fix to query_update(None)
  CHANGES/792.bugfix.rst
  tests/test_update_query.py
  yarl/_url.py
Labels: bot:chronographer:provided

#782 Change to SPDX conform license string
  setup.py
Labels: bot:chronographer:skip

#741 Keep absolute paths absolute when normalising.
  CHANGES/536.bugfix.rst
  tests/test_normalize_path.py
  yarl/_url.py
Labels: bot:chronographer:provided

#704 Add URL.joinpath(*elements, encoding=False) to build a URL with multiple new path elements
  CHANGES/704.feature.rst
  docs/api.rst
  tests/test_url.py
  yarl/__init__.pyi
  yarl/_url.py
Labels: bot:chronographer:provided
