Repository aio-libs/yarl, pull requests merged in 2024-11, with the labels that each got.

#1410 Remove `noexcept` from `_restore_ch`
  yarl/_quoting_c.pyx
Labels: bot:chronographer:skip

#1414 Make error messages have details of incorrect type when `port` is not int in `URL.build()`
  CHANGES/1414.feature.rst
  tests/test_url_build.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1413 Correctly handle zero explicit_port
  CHANGES/1413.bugfix.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1412 📦 Cap Cython under Python 3.12+ below v3.1
  CHANGES/1411.bugfix.rst
  CHANGES/1411.packaging.rst
  CHANGES/1412.bugfix.rst
  CHANGES/1412.packaging.rst
  packaging/pep517_backend/_backend.py
Labels: dependencies, bot:chronographer:provided

#1417 Add non-encoded joinpath benchmark
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1416 Small cleanups to URL.join
  yarl/_url.py
Labels: bot:chronographer:skip

#1418 Improve performances of `URL.joinpath`
  CHANGES/1418.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1420 Increment version to 1.17.3.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1422 Improve performance of converting a URL to a string
  CHANGES/1422.misc.rst
  yarl/_parse.py
Labels: bot:chronographer:provided

#1424 Remove internal `_default_port` property
  yarl/_url.py
Labels: bot:chronographer:skip

#1428 Revert "Temporarily downgrade codecov-action to 5.0.3 to fix CI"
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#1421 Allow replacing path without replacing query or fragment
  CHANGES/111.feature.rst
  CHANGES/1421.feature.rst
  docs/api.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1415 Add aiohttp tests to CI
  .github/workflows/aiohttp.yml
  CHANGES/1415.contrib.rst
Labels: bot:chronographer:provided

#1430 Increment version to 1.18.1.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1434 Make `from_parts` a LRU to increase the chance we can preserve the internal cache
  CHANGES/1434.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1432 Add a cache for building encoded URLs
  CHANGES/1432.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1436 Avoid caching the constructed URL when altering the query string
  CHANGES/1436.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1435 Release 1.18.1
  CHANGES.rst
  CHANGES/1432.misc.rst
  CHANGES/1434.misc.rst
  CHANGES/1436.misc.rst
  yarl/__init__.py
Labels: bot:chronographer:provided

#1438 Increase allowed upload time for the release
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#1437 Increment version to 1.18.2.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1439 Release 1.18.2
  CHANGES.rst
  yarl/__init__.py
Labels: bot:chronographer:skip
