Repository aio-libs/yarl, pull requests merged in 2024-10, with the labels that each got.

#1170 Improve performance of converting URL to a string
  CHANGES/1170.misc.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1172 Remove reference to alpine linux from readme
  README.rst
Labels: bot:chronographer:skip

#1176 Improve performance of _encode_host
  CHANGES/1176.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1177 Cleanup some unnecessary internal property accesses
  yarl/_url.py
Labels: bot:chronographer:skip

#860 🧪 Integrate Hypothesis in tests
  .pre-commit-config.yaml
  CHANGES/860.contrib.rst
  requirements/test.txt
  tests/test_quoting.py
Labels: enhancement, bot:chronographer:provided

#1169 Migrate to using propcache for property caching
  .github/ISSUE_TEMPLATE/bug_report.yml
  .pre-commit-config.yaml
  CHANGES/1169.packaging.rst
  README.rst
  docs/conf.py
  docs/index.rst
  requirements/test.txt
  setup.cfg
  tests/test_helpers.py
  yarl/_helpers.py
  yarl/_helpers_c.pyi
  yarl/_helpers_c.pyx
  yarl/_helpers_py.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1181 Increment version to 1.14.1.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1182 Add test coverage for handling port 0
  tests/test_url.py
Labels: bot:chronographer:skip

#1189 Fix with_scheme checks when passed scheme is not lowercase
  CHANGES/1189.misc.rst
  tests/test_url_update_netloc.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1190 Add a cache to parsing the host when encoding hosts
  CHANGES/1190.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1191 Add benchmark script for URLs
  url_benchmark.py
Labels: bot:chronographer:skip

#1194 Add benchmarks for with_query
  url_benchmark.py
Labels: bot:chronographer:skip

#1195 Improve URL benchmarks to better match real world use cases
  url_benchmark.py
Labels: bot:chronographer:skip

#1193 Improve performance of generating query strings from mappings that contain sequences
  CHANGES/1193.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1196 Improve typing for _make_child
  yarl/_url.py
Labels: bot:chronographer:skip

#1197 Add benchmarks to converting URLs to strings
  url_benchmark.py
Labels: bot:chronographer:skip

#1199 Use comparison chain for validating port numbers
  yarl/_url.py
Labels: bot:chronographer:skip

#1198 Improve performance of converting of converting URLs to strings
  CHANGES/1198.misc.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1200 Remove unused code in _quoting_c.pyi
  yarl/_quoting_c.pyi
Labels: bot:chronographer:skip

#1201 Simplify raw_parts branching
  yarl/_url.py
Labels: bot:chronographer:skip

#1202 Replace not with not equal operator in _validate_authority_uri_abs_path
  yarl/_url.py
Labels: bot:chronographer:skip

#1204 Start building armv7l wheels
  .github/workflows/ci-cd.yml
  CHANGES/1204.feature.rst
Labels: bot:chronographer:provided

#1205 Collapse multiple statements that can be replaced with ternary operators
  yarl/_url.py
Labels: bot:chronographer:skip

#1206 Combine nested if statements in quoting_py
  yarl/_quoting_py.py
Labels: bot:chronographer:skip

#1207 Fix changelog type for #1189
  CHANGES/1189.bugfix.rst
Labels: bot:chronographer:skip

#1209 Increment version to 1.15.1.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1210 Integrate codspeed benchmarking
  .github/workflows/ci-cd.yml
  requirements/test.txt
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1211 Add quoting benchmarks
  tests/test_quoting_benchmarks.py
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1215 Fix benchmarks including pytest overhead
  tests/test_quoting_benchmarks.py
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1218 Small speed up to making IPv6 URLs
  yarl/_url.py
Labels: bot:chronographer:skip

#1217 Remove unused requote argument from _make_netloc
  yarl/_url.py
Labels: bot:chronographer:skip

#1221 Add typing to benchmark tests
  .pre-commit-config.yaml
  tests/test_quoting_benchmarks.py
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1225 Add additional URL benchmarks for altering URLs
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1222 Improve URL.build performance
  CHANGES/1222.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1227 Improve performance of building non-encoded URLs
  yarl/_url.py
Labels: bot:chronographer:skip

#1226 Speed up methods that create new URL objects
  CHANGES/1226.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1229 Avoid re-parsing the netloc when changing user/pass/host/port
  CHANGES/1229.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1230 Add missing type for host_subcomponent to the internal cache
  yarl/_url.py
Labels: bot:chronographer:skip

#1235 Split wheel builds into manylinux and musllinux groups to speed up CI
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-build-wheel.yml
Labels: bot:chronographer:skip

#1236 Adjust many url and many hosts benchmarks to reduce CI run time
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1238 Disable running hypothesis tests under cibuildwheel
  .github/workflows/reusable-build-wheel.yml
  tests/test_quoting.py
Labels: bot:chronographer:skip

#1239 Fix building musllinux wheels during release
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-build-wheel.yml
Labels: bot:chronographer:skip

#1240 Fix hypothesis still running during wheel build
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-build-wheel.yml
  tests/test_quoting.py
Labels: bot:chronographer:skip

#1241 Fix manylinux wheels not building on release
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#1242 Fix building wheels during release
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-build-wheel.yml
Labels: bot:chronographer:skip

#1243 Ensure cibuildwheel does not attempt to build pypi wheels
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#1233 Increment version to 1.15.2.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1234 Improve performance of converting URL to string
  CHANGES/1234.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1244 Reduce iterations of query string benchmarks
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1247 Add more benchmarks for common aiohttp calls
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1249 Add benchmark for truediv path joins
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1248 Avoid normalizing child paths when there are no dots in the path
  CHANGES/1248.misc.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1250 Avoid copying list to reverse segments when making children
  CHANGES/1250.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1253 Add some additional extend_query benchmarks for common cases
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1254 Add additional benchmarks for common cases
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1252 Check val.netloc instead of self.absolute internally
  yarl/_url.py
Labels: bot:chronographer:skip

#1251 Avoid some string copy in extend_query
  yarl/_url.py
Labels: bot:chronographer:skip

#1257 Add benchmarks for query strings with int values
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1256 Optimize building query strings with MultiDict
  CHANGES/1256.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1259 Improve performance of constructing query strings with ``int`` values
  CHANGES/1259.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1261 Increment version to 1.15.3.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1203 Drop support for Python 3.8
  .codecov.yml
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-linters.yml
  .pre-commit-config.yaml
  CHANGES/1203.breaking.rst
  setup.cfg
  tests/test_quoting.py
  tests/test_url_query.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1266 Optimize branching _encode_host for common case
  yarl/_url.py
Labels: bot:chronographer:skip

#1264 Improve performance of constructing URLs from unencoded string
  yarl/_url.py
Labels: bot:chronographer:skip

#1269 Add benchmarks for empty username and password
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1268 Simplify processing of username and password for unencoded URLs
  yarl/_url.py
Labels: bot:chronographer:skip

#1271 Add a fast path for URL construction when the netloc is the host
  CHANGES/1271.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1273 Add benchmark for human_repr
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1277 Avoid splitting the netloc for simple cases when constructing URL
  yarl/_url.py
Labels: bot:chronographer:skip

#1278 Add benchmarks for calling origin() on a URL with credentials
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1274 Small speed up to human_repr
  yarl/_url.py
Labels: bot:chronographer:skip

#1275 Improve performance of calling origin() for URLs with credentials
  yarl/_url.py
Labels: bot:chronographer:skip

#1279 Make validate_host a required argument to _encode_host
  yarl/_url.py
Labels: bot:chronographer:skip

#1265 Fix `URL.build` not validating that `path` has a leading slash when passing `authority`
  CHANGES/1265.bugfix.rst
  tests/test_url_build.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1287 Small speed up to with_path
  yarl/_url.py
Labels: bot:chronographer:skip

#1283 Increment version to 1.15.4.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1284 Include port in the fast path for building the network location
  yarl/_url.py
Labels: bot:chronographer:skip

#1290 Add test to ensure query quoter is not off by one
  tests/test_quoting.py
Labels: bot:chronographer:skip

#1289 Add more quoting benchmarks
  tests/test_quoting_benchmarks.py
Labels: bot:chronographer:skip

#1291 Add unquoting benchmarks
  tests/test_quoting_benchmarks.py
Labels: bot:chronographer:skip

#1288 Improve quoter performance when all characters are safe
  CHANGES/1288.misc.rst
  yarl/_quoting_c.pyx
Labels: bot:chronographer:provided

#1292 Use faster Python unicode API for unquoter
  CHANGES/1292.misc.rst
  yarl/_quoting_c.pyx
Labels: bot:chronographer:provided

#1293 Avoid creating a new unquoted string if nothing changes
  CHANGES/1293.misc.rst
  yarl/_quoting_c.pyx
Labels: bot:chronographer:provided

#1294 Fix path quoting benchmarks to use the same quoting config as production
  tests/test_quoting_benchmarks.py
Labels: bot:chronographer:skip

#1295 Add query string benchmarks
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1298 Remove redundant hypothesis pytest mark
  tests/test_quoting.py
Labels: bot:chronographer:skip

#1299 Add benchmark for building a URL with query
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1300 Fix query benchmarks to avoid testing property cache hits
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1297 Improve performance of `URL.build` by avoiding operations
  CHANGES/1297.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1302 Increment version to 1.15.5.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1303 Add benchmarks for making and building URLs without a host
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1304 Small cleanups to making children paths
  CHANGES/1304.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1305 Improve performance of the `URL.extend_query` method
  CHANGES/1305.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1310 Fix URL.origin benchmark to avoid testing the cache
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1307 Improve performance of the `URL.with_path` method
  CHANGES/1307.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1311 Improve query string benchmarking
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1312 Small performance improvement for query strings with int values
  yarl/_url.py
Labels: bot:chronographer:skip

#1306 Improve performance of the `URL.origin` method
  CHANGES/1306.misc.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1308 Improve performance of the `URL.with_query` method
  CHANGES/1308.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1313 Refactor `URL.join` to avoid intermediate dict
  CHANGES/1313.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1314 Add update_query benchmarks
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1309 Improve performance of the `URL.update_query` method
  CHANGES/1309.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1315 Improve performance of URL equality checks
  CHANGES/1315.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1317 Improve performance of with_fragment
  CHANGES/1317.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1316 Improve performance of methods that modify the network location
  CHANGES/1316.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1323 Add missing benchmark for less common operations
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1318 Improve performance of calculating the URL hash
  CHANGES/1318.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1322 Improve performance of `URL.with_scheme`
  CHANGES/1322.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1320 Improve performance of URL.with_name
  CHANGES/1320.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1319 Improve performance of `URL.relative`
  CHANGES/1319.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1324 Improve test coverage for `URL.parent`
  tests/test_url.py
Labels: bot:chronographer:skip

#1325 Additional cleanups for `URL.parent` tests
  tests/test_url.py
Labels: bot:chronographer:skip

#1321 Improve performance of `URL.parent`
  CHANGES/1321.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1328 Improve performance of `with_query` when passing an empty value
  CHANGES/1328.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1329 Add benchmark for calling `update_query` with a query string
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1327 Avoid multiple conversions in `URL.update_query` with passing a `Mapping` or `Sequence`
  CHANGES/1327.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1332 Increment version to 1.15.6.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1333 Add codspeed badge to README
  README.rst
Labels: bot:chronographer:skip

#1335 Small internal code cleanups
  yarl/_url.py
Labels: bot:chronographer:skip

#1334 Reduce duplicate code to construct URL from a tuple
  yarl/_url.py
Labels: bot:chronographer:skip

#1336 Small performance improvement for constructng new URL objects
  CHANGES/1336.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1337 Add a benchmark for accessing the raw_host with an empty cache
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1341 Add benchmarks for many ipv4/ipv6 hosts
  tests/test_url_benchmarks.py
Labels: bot:chronographer:skip

#1343 Add additional test coverage for invalid URLs
  .coveragerc
  tests/test_url.py
Labels: bot:chronographer:skip

#1344 Add tests for disallowed unicode characters
  tests/test_url.py
Labels: bot:chronographer:skip

#1346 Make _normalize_path a staticmethod
  yarl/_url.py
Labels: bot:chronographer:skip

#1345 Break out functions that do not need decorated methods
  CHANGES/1345.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1347 Add additional test case for unicode decomposition normalization
  tests/test_url.py
Labels: bot:chronographer:skip

#1342 Fix blocking I/O to load python code when the network location contains non-ascii characters
  .coveragerc
  CHANGES/1342.bugfix.rst
  docs/spelling_wordlist.txt
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1350 Extract `_query_var` into its own function
  yarl/_url.py
Labels: bot:chronographer:skip

#1352 Remove unused sentinel code
  yarl/_url.py
Labels: bot:chronographer:skip

#1354 Cleanup constant naming in `_url.py`
  yarl/_url.py
Labels: bot:chronographer:skip

#1351 Extract `_make_netloc` from URL object
  yarl/_url.py
Labels: bot:chronographer:skip

#1353 Extract staticmethods from URL object
  tests/test_normalize_path.py
  yarl/_url.py
Labels: bot:chronographer:skip

#1348 Move lru cache from inside of `_encode_host` to outside
  CHANGES/1348.breaking.rst
  docs/api.rst
  tests/test_cache.py
  yarl/__init__.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1355 Move quoters to their own module
  yarl/_quoters.py
  yarl/_url.py
Labels: bot:chronographer:skip

#1357 Fix setting the idna_encode_size
  CHANGES/1357.breaking.rst
  tests/test_cache.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1358 Add missing test coverage for `URL.update_query`
  tests/test_url_query.py
Labels: bot:chronographer:skip

#1356 Move query string functions into their own module
  yarl/__init__.py
  yarl/_query.py
  yarl/_url.py
Labels: bot:chronographer:skip

#1359 Add missing coverage for `URL.build`
  tests/test_url_build.py
Labels: bot:chronographer:skip

#1360 Move URL parsing functions to their own module
  yarl/_parse.py
  yarl/_url.py
Labels: bot:chronographer:skip

#1361 Move human_quote into the quoters module
  yarl/_quoters.py
  yarl/_url.py
Labels: bot:chronographer:skip

#1362 Move path functions into their own module
  tests/test_normalize_path.py
  yarl/_path.py
  yarl/_url.py
Labels: bot:chronographer:skip

#1363 Fix loop variable being redefined in `cache_configure`
  CHANGES/1363.breaking.rst
  tests/test_cache.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1366 Add coverage for passing encoded `SplitResult` to create a `URL`
  tests/test_url.py
Labels: bot:chronographer:skip

#1367 Add coverage for invalid IDNA encoding
  tests/test_url.py
Labels: bot:chronographer:skip

#1368 Remove unreachable authority absolute path check in `URL.__new__`
  yarl/_url.py
Labels: bot:chronographer:skip

#1370 Add test coverage for creating URLs from pre-encodeded str
  tests/test_url.py
Labels: bot:chronographer:skip

#1369 Move `split_url` cache around encoding the URL
  CHANGES/1369.misc.rst
  tests/test_url.py
  yarl/_parse.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1373 Increment version to 1.16.1.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip
