Repository aio-libs/yarl, pull requests merged in 2024-09, with the labels that each got.

#1074 🧪🚑 Fix coverage.py-included paths @ XML
  .coveragerc
Labels: bot:chronographer:skip

#1066 Add additional coverage for joining urls
  tests/test_url.py
Labels: bot:chronographer:skip

#1070 Adapt aiohttp reify implementation to replace internal cached_property
  CHANGES/1070.misc.rst
  tests/test_helpers.py
  yarl/_helpers.py
  yarl/_helpers_c.pyi
  yarl/_helpers_c.pyx
  yarl/_helpers_py.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1076 Remove fallback to getservbyname in _get_default_port
  CHANGES/1076.breaking.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1079 Cleanup asyncio reference in the 1.9.7 changelog
  CHANGES.rst
Labels: bot:chronographer:skip

#1080 Increment version to 1.9.8.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1083 Fix codecov blocking merges
  .codecov.yml
Labels: bot:chronographer:skip

#1081 Improve performance of handling ports in the URL
  CHANGES/1081.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1085 🧪 Integrate `covdefaults` into coverage.py
  .codecov.yml
  .coveragerc
  .github/workflows/ci-cd.yml
  requirements/test.txt
Labels: bot:chronographer:skip

#1086 Cache IP Address parsing
  CHANGES/1086.feature.rst
  docs/api.rst
  tests/test_cache.py
  yarl/__init__.pyi
  yarl/_url.py
Labels: bot:chronographer:provided

#1084 Add typing to URL
  .codecov.yml
  .coveragerc
  CHANGES/1084.contrib.rst
  CHANGES/1084.feature.rst
  tests/test_url.py
  yarl/__init__.pyi
  yarl/_helpers.py
  yarl/_quoting_c.pyi
  yarl/_quoting_py.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1087 Restore codecov patch requirement to 100%
  .codecov.yml
Labels: bot:chronographer:skip

#1090 Add rc to the spelling wordlist
  docs/spelling_wordlist.txt
Labels: bot:chronographer:skip

#1093 Increment version to 1.9.9.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1099 Increment version to 1.9.10.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1101 Adjust missing type changelog message to be attr instead of meth
  CHANGES.rst
Labels: bot:chronographer:skip

#1100 Introduce absolute cached property
  CHANGES/1100.feature.rst
  docs/api.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1082 RFC3986 compatible URL.join honoring empty segments again
  CHANGES/1039.bugfix.rst
  CHANGES/1082.bugfix.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1106 Increment version to 1.9.11.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1104 Avoid trying to parse strings that cannot be IP Addresses
  CHANGES/1104.misc.rst
  tests/test_url_build.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1107 Fix `TypeError` with `MultiDictProxy` and Python 3.8
  CHANGES/1084.bugfix.rst
  CHANGES/1105.bugfix.rst
  CHANGES/1107.bugfix.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1110 Increment version to 1.9.12.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1095 Replace all `Optional` with `Union`
  CHANGES/1095.contrib.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1114 Increment version to 1.10.0.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#898 Add new method `without_query_params` to drop query keys
  CHANGES/1010.feature.rst
  CHANGES/774.feature.rst
  CHANGES/898.feature.rst
  docs/api.rst
  tests/test_url_query.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1112 Significantly speed up parsing netloc in URL objects
  CHANGES/1112.misc.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1115 Reclassify #1113 as a feature
  CHANGES/1050.contrib.rst
  CHANGES/1050.feature.rst
  CHANGES/1113.feature.rst
Labels: bot:chronographer:skip

#1117 Add types to the internal cache
  CHANGES/1117.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1118 Fix joining a path when the existing path is empty
  CHANGES/1118.bugfix.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1120 Fix merging of wheels during release process
  .github/workflows/reusable-build-wheel.yml
Labels: bot:chronographer:skip

#1121 Adjust formatting of changelog message for #1095
  CHANGES/1095.contrib.rst
Labels: bot:chronographer:skip

#1124 Increment version to 1.10.1.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1123 Simplify computing ports
  CHANGES/1123.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1122 Optimize cython cached_property implementation
  CHANGES/1122.misc.rst
  yarl/_helpers_c.pyx
Labels: bot:chronographer:provided

#1125 Small optimization to encoding hosts
  CHANGES/1125.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1126 Avoid quoting empty strings when building URLs
  CHANGES/1126.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1129 Remove useless path replacement in with_query
  yarl/_url.py
Labels: bot:chronographer:skip

#1130 Improve performance of URL.update_query
  CHANGES/1130.misc.rst
  tests/test_update_query.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1132 Refactor _get_str_query to avoid intermediate variable
  yarl/_url.py
Labels: bot:chronographer:skip

#1131 Optimize _query_var for ``str`` objects
  CHANGES/1131.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1133 Increment version to 1.11.0.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1128 Add extend_query method
  CHANGES/1128.feature.rst
  docs/api.rst
  tests/test_update_query.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1135 Increment version to 1.11.1.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1137 Small speed up to normalizing the path
  CHANGES/1137.misc.rst
  tests/test_normalize_path.py
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1136 Allow empty hosts for schemes that do not require them
  CHANGES/1136.bugfix.rst
  tests/test_url_parsing.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1138 Allow scheme replacement for relative URLs if the target scheme does not require a host
  CHANGES/1138.bugfix.rst
  CHANGES/280.bugfix.rst
  tests/test_url_update_netloc.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1140 Cleanup tense of changelog messages
  CHANGES/1136.bugfix.rst
  CHANGES/1138.bugfix.rst
  CHANGES/1139.feature.rst
Labels: bot:chronographer:skip

#1142 Increment version to 1.11.2.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1143 Small performance improvements to checking for chars in paths
  CHANGES/1143.misc.rst
  yarl/_url.py
Labels: bot:chronographer:provided

#1151 Restore unquoting of %2F in paths
  CHANGES/1151.breaking.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1150 Add path_safe method
  CHANGES/1150.feature.rst
  docs/api.rst
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1153 Increase release timeout from 7 to 14 minutes
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#1154 Release 1.12.1
  CHANGES.rst
  yarl/__init__.py
Labels: bot:chronographer:skip

#1155 Increment verson to 1.12.2.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1160 Add versionadded to path_safe
  docs/api.rst
Labels: bot:chronographer:skip

#1159 Add `host_subcomponent` property
  CHANGES/1159.feature.rst
  docs/api.rst
  docs/spelling_wordlist.txt
  tests/test_url.py
  yarl/_url.py
Labels: bot:chronographer:provided

#954 Validate ASCII host values
  CHANGES/880.bugfix.rst
  CHANGES/954.bugfix.rst
  docs/api.rst
  docs/spelling_wordlist.txt
  tests/test_cache.py
  tests/test_url.py
  tests/test_url_build.py
  tests/test_url_update_netloc.py
  yarl/_url.py
Labels: bug, bot:chronographer:provided

#1162 Increment version to 1.13.1.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip

#1163 Improve performance of building URLs with authority
  CHANGES/1163.misc.rst
  tests/test_url_build.py
  yarl/_url.py
Labels: bot:chronographer:provided

#1165 Increment version to 1.13.2.dev0
  yarl/__init__.py
Labels: bot:chronographer:skip
